name: Required By Main Only

on:
  pull_request:
    branches:
      - main
  merge_group:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

jobs:
  build-docker-image:
    uses: ./.github/workflows/build-docker-image.yml