name: Required workflow

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
  workflow_call:
  workflow_dispatch:

jobs:
  Required-Steps:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag supervisord-playground:$(date +%s)